require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 7