require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/migrate/20170420210630_devise_create_users.rb'
    - 'db/schema.rb'
    - 'tmp/**/*'

Metrics/LineLength:
  Max: 160

Metrics/BlockLength:
  Max: 100

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10