default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: econseils-development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: econseils-test
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *default
  database: econseils-production