default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: reso-development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: reso-test
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *default
  database: reso-production
